import Head from "next/head";
import Link from "next/link";
import Layout from "../../containers/Layout/Layout";
import styles from '../about/about.module.css';
import styled from 'styled-components';
import {css} from '@emotion/css';

import Button from "../../components/Button/Button";
// const Title = styled.h1 `
//   font-size: ${props => props.fontSize}em;
//   text-align: ${(props) => props.align};
//   color: palevioletred;
// `;
export default function About() {
  const color = 'white';
  const backgroundColor = 'red';
  return (
    <>
    <Head>
        <title>About US</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
    <Layout>
    <div className={styles.About}>
        {/* <Title align="left" fontSize="20">
          about
        </Title> */}
        <p className={css`
            padding: 32px;
            background-color: ${backgroundColor};
            font-size: 25px;
            border-radius:4px;
            &:hover{
              color: ${color};
            }        
        `}>this is about page</p>
        <br/>
        <Button type="primary">
            click here
        </Button>   
        <Link href="/">
              Home
        </Link>



    </div>
    </Layout>
    </>   
  )
}