import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Layout from '../containers/Layout/Layout'
export default function Home(props) {
  console.log('====================================')
  console.log(props,'props')
  console.log('====================================')
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
          <main className={styles.main}>
                <h1 className={styles.title}>
                  Welcome to React advanced 
                </h1>
                <Link href="/about">
                AboutUS 
                </Link>
                <Link href="/blog/article/article">
                AboutUS 
                </Link>
          </main>
      </Layout>
    </div>
  )
}
// Home.getInitialProps = async (ctx) => {
//   const res = await fetch('https://api.github.com/repos/vercel/next.js')
//   const json = await res.json()
//   return { something : json }
// }